<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <OutputType>Library</OutputType>
	  <UseWPF>true</UseWPF>
	  <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="VPet-Simulator.Core" Version="1.1.0.66">
		  <ExcludeAssets>runtime</ExcludeAssets><!--不复制到输出目录-->
	  </PackageReference>
	  <PackageReference Include="VPet-Simulator.Windows.Interface" Version="1.1.0.66" >
		  <ExcludeAssets>runtime</ExcludeAssets>
	  </PackageReference>
  </ItemGroup>

</Project>
